### ISSUE TITLE
Cleanup EQ and CQ and add wait objects.

### ISSUE THREAD

**Issue by bturrubiates** [ofi-cray/libfabric-cray#120]
- [x] #115 Implement generic queue. 
- [x] #118 Update EQ to use generic queue.
- [x] #119 Update CQ to use generic queue.
- [x] #116 Add wait objects to EQ.
- [x] Cleanup the EQ and CQ code and fix return values. (Miscellaneous fixes)
