### ISSUE TITLE
Handle multiple API versions

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#1221]
Functions:
- [x] new addr format (#1189), PR #1212 @e-harvey #1223 

Special case argument handling:
- [x] __cq_read_err (unknown source address reporting #1147) @jshimek #1224 
- [x] do not check number of counters for API < 1.5 (#1169) @jshimek #1225 
- [x] do not check mr_iov_limit for API < 1.5 (#1151) @chuckfossen #1226 
- [x] FI_NOTIFY_FLAGS_ONLY, check API version on opening EP (#1180) @jshimek #1227 
- [x] auth key support (ofiwg/libfabric#2629) @jswaro #1228 

Runtime check:
- [x] new cntr methods (#1166) @jshimek #1229 

No op:
- FI_SYNC_ERR (#1170), possibly reconsider later
- FI_REMOTE_COMM/FI_LOCAL_COMM (#1152), only supports FI_REMOTE_COMM anyway
- multicast (ofiwg/libfabric#2627),  done upstream 
- comp list (ofiwg/libfabric#2628), waiting for upstream

**Comment by sungeunchoi** [comment]
Functions:
- new addr format (#1189), PR #1212 

Special case argument handling:
- __cq_read_err (unknown source address reporting #1147)
- do not check number of counters for API < 1.5 (#1169)
- do not check mr_iov_limit for API < 1.5 (#1151)
- FI_NOTIFY_FLAGS_ONLY, check API version on opening EP (#1180)
- auth key support (ofiwg/libfabric#2629)

Runtime check:
- new cntr methods (#1166)
- fi_mr_refresh (#1217 )

No op:
- FI_SYNC_ERR (#1170), possibly reconsider later
- FI_REMOTE_COMM/FI_LOCAL_COMM (#1152), only supports FI_REMOTE_COMM anyway
- multicast (ofiwg/libfabric#2627),  done upstream 
- comp list (ofiwg/libfabric#2628), waiting for upstream

**Comment by sungeunchoi** [comment]
ofiwg/libfabric#2772 should help with these issues.

**Comment by sungeunchoi** [comment]
Upstream commit https://github.com/ofiwg/libfabric/pull/2778/commits/258c419e4d6f8a7c2d09b4424291de463ed5f332 added api_version to struct fid_fabric.

**Comment by sungeunchoi** [comment]
These updates should include tests for pre-1.5 and 1.5.

**Comment by jshimek** [comment]
Closing as all the related components issues are completed
