### ISSUE TITLE
Working fabtests simple/fi_rdm_pingpong

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#5]
- [x] VC SMSG connection setup using datagram subsystem #97
- [x]  need large page slab allocator that registers memory against gnix_nic's #98
- [x] need simple freelist for gnix_fab_reqs #100
- [x] Code up basic fi_send and fi_recv #175

**Comment by hppritcha** [comment]
This is a tracking issue for the tasks that needed to be completed for first light for an fi_send/fi_recv over the GNI provider.  In this first milestone, it is only required to send a short message using GNI_SmsgSend(wTag).

**Comment by hppritcha** [comment]
Depends on

- [ ]  VC SMSG connection setup using datagram subsystem #97
- [ ] need large page slab allocator that registers memory against gnix_nic's #98

**Comment by hppritcha** [comment]
Last step to verify here is that we can pass the fi_rdm_pingpong for the range of messages allowed using the `GNI_SmsgSend` path.

**Comment by hppritcha** [comment]
verified with a slightly modified version of the osu latency port to libfab that pingpong is working for
the message sizes we support for purely GNI_Smsg based transfers.
